name: Get Players Data

on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-and-store-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch Players Data
        run: python scripts/get_players_data.py

      - name: Commit and push changes
        run: |
          git config --local user.email "rahnel.taavi+data-update-bot@gmail.com"
          git config --local user.name "Data Update Bot"
          git_status=$(git status --porcelain)
          if [ -n "$git_status" ]; then
            git add -A
            git commit -m "Automated player data update, $(date +'%Y-%m-%d %H:%M:%S') UTC"
            git push
          else
            echo "No changes to commit."
          fi
